bbs/bbs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('form/', include('message.urls'))
]

bbs/message/urls.py
from django.urls import path
from . import views

app_name = 'message'
urlpatterns = [
    path('index/', views.getform, name='form_index')
]

bbs/message/models.py
# -*- coding: utf-8 -*-
from django.db import models

# Create your models here.


class UserMessage(models.Model):
    object_id = models.CharField(max_length=50,default='', primary_key=True, verbose_name=u"主键")
    name = models.CharField(max_length=20,null=True, blank=True, default="匿名用户", verbose_name=u'用户名')
    email = models.EmailField(verbose_name=u'邮箱')
    address = models.CharField(max_length=100, verbose_name=u'联系地址')
    message = models.CharField(max_length=500, verbose_name=u"留言信息")

    class Meta:
        verbose_name = u'用户留言信息'
        verbose_name_plural = verbose_name

bbs/message/views.py
from django.shortcuts import render
from .models import UserMessage
# Create your views here.


def getform(request):
    # queryset类型，支持for循环
    # all_message = UserMessage.objects.filter(name='Foo', address='Beijing')
    # all_message.delete()
    # for message in all_message:
    #     print(message.name)
    #     message.delete()
    name = request.POST.get('name', '')
    message = request.POST.get('message', '')
    address = request.POST.get('address', '')
    email = request.POST.get('email', '')
    user_message = UserMessage()
    user_message.name = name
    user_message.message = message
    user_message.address = address
    user_message.email = email
    user_message.object_id = 'helloword2'

    user_message.save()

    # message = None
    # all_messages = UserMessage.objects.filter(name='Foo')
    # if all_messages:
    #     message = all_messages[0]

    return render(request, 'message/message_form.html', {
        'my_message': message
    })

bbs/templates/message/message_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>form</title>
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
<form action="{% url 'message:form_index'  %}" method="post" class="smart-green">
    <h1>留言信息
        <span>请留下你的信息.</span>
    </h1>
    <label>
        <span>姓名 :</span>
        <input id="name" type="text" name="name" class="error" placeholder="请输入您的姓名"/>
        <div class="error-msg"></div>
    </label>

    <label>
        <span>邮箱 :</span>
        <input id="email" type="email" value="" name="email" placeholder="请输入邮箱地址"/>
        <div class="error-msg"></div>
    </label>

    <label>
        <span>联系地址 :</span>
        <input id="address" type="text" value="" name="address" placeholder="请输入联系地址"/>
        <div class="error-msg"></div>
    </label>

    <label>
        <span>留言 :</span>
        <textarea id="message" name="message"  placeholder="请输入你的建议"></textarea>
        <div class="error-msg"></div>
    </label>
    <div class="success-msg"></div>
    <label>
        <span>&nbsp;</span>
        <input type="submit" class="button" value="提交"/>
    </label>
    {% csrf_token %}
</form>
</body>
</html>