myblog/blog/urls.py
from django.urls import path
from . import views

# 命名空间
app_name = 'blog'
urlpatterns = [
	# ex: /blog/
	path('index/', views.index, name='index'),
	path('article/<int:article_id>/', views.article, name='article'),
	path('edit/<int:article_id>/', views.edit, name='edit'),
	path('edit/action/', views.edit_action, name='edit_action'),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')), 
]

myblog/blog/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
	title = models.CharField(max_length=32, default='Title')
	content = models.TextField(null=True)
	# 创建对象的时候自动获得当前日期
	pub_time = models.DateTimeField(auto_now=True)
	# pub_time = models.DateTimeField(null=True)
	# 定义后台的标题
	def __str__(self):
		return self.title

myblog/blog/views.py
from django.http import HttpResponse, HttpResponseRedirect
# from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from . import models
from django.utils import timezone

# Create your views here.
# use common templates.


def index(request):
	# 倒序获得文章列表
	articles = models.Article.objects.order_by('-id')
	return render(request, 'blog/index.html', {'articles': articles})

def article(request, article_id):
	article = models.Article.objects.get(pk=article_id)
	return render(request, 'blog/article.html', {'article': article})
		
def edit(request, article_id):
	if str(article_id) == '0':
		# 新增
		return render(request, 'blog/edit.html')
	article = models.Article.objects.get(pk=article_id)
		# 编辑
	return render(request, 'blog/edit.html', {'article': article})

def edit_action(request):
	title = request.POST.get('title', 'TITLE')
	content = request.POST.get('content', 'CONTENT')
	article_id = request.POST.get('article_id', 0)
	if article_id == '0':
		# 新增
		models.Article.objects.create(title=title, content=content)
		articles = models.Article.objects.all()
		return render(request, 'blog/index.html', {'articles': articles})
	# 保存
	article = models.Article.objects.get(pk=article_id)
	article.title = title
	article.content = content
	article.save()
	return render(request, 'blog/article.html', {'article': article})

myblog/templates/blog/article.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Article Page</title>
</head>
<body>
	<h2>{{article.title}}</h2>
	<p>{{article.content}}</p>
	<a href="{% url 'blog:edit' article.id %}">修改文章</a>
	<a href="{% url 'blog:index' %}">返回首页</a>
</body>
</html>

myblog/templates/blog/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Edit Page</title>
</head>
<body>
<h2>编辑你的博客</h2>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'blog:edit_action' %}"  method="post">
{% csrf_token %}
	<input type="hidden" name="article_id" value="{{article.id | default:'0'}}">
	<!-- Django模板中出现了不存在的变量，不会报错，只会给个空值 -->
    <label>文章标题</label><input type="text" name="title" value="{{article.title}}"><br>
    <label>文章内容</label><input type="text" name="content" value="{{article.content}}" /><br>
    
<input type="submit" value="Submit">
</form>
</body>
</html>

myblog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Blog</title>
</head>
<body>
	<h2>
		<a href="{% url 'blog:edit' 0 %}">新文章</a>
	</h2>
	{% for article in articles %}
		<a href="{% url 'blog:article' article.id %}">{{article.title}}</a>
		<br>
	{% endfor %}
</body>
</html>